<?php
	include("course.php");
	$events=<<XML
	<event>
		<eventplaces>
			<eventplace>
			</eventplace>
			<eventdate>
			</eventdate>
			<eventstart>
			</eventstart>
		</eventplacse>
		<people>
			<name>
			</name>
			<birthdate>
			</birthdate>
			<idnumber>
			</idnumber>
			<phonenumber>
			</phonenumber>
		</people>
	</event>
	XML;
	$xml = new SimpleXMLElement($events);
	$xml->saveXML("../tmp/summary.xml");
?>
